In [61]:
import rasterio
from rasterio.windows import Window
from pathlib import Path
from pyproj import Transformer
import pandas as pd
import geopandas as gpd
from tqdm.auto import tqdm
from rasterio.crs import CRS

In [62]:
confirmed_products_dir = Path('../../dist-s1-research/marshak/Zg_validation_variation/val_products_transformer_optimized-max10_processed_2026-02-05')
dist_s1_ts_dir = list(confirmed_products_dir.glob('*/'))
dist_s1_ts_dir[:2]

[PosixPath('../../dist-s1-research/marshak/Zg_validation_variation/val_products_transformer_optimized-max10_processed_2026-02-05/treelosswet__20KNG'),
 PosixPath('../../dist-s1-research/marshak/Zg_validation_variation/val_products_transformer_optimized-max10_processed_2026-02-05/waternew__17MPT')]

In [63]:
len(dist_s1_ts_dir)

85

In [77]:
TS_DIR = dist_s1_ts_dir[0]
TS_DIR

PosixPath('../../dist-s1-research/marshak/Zg_validation_variation/val_products_transformer_optimized-max10_processed_2026-02-05/treelosswet__20KNG')

In [ ]:
TS_DIR = Path(TS_DIR)
MGRS_TILE_ID = TS_DIR.name.split('__')[1]
MGRS_TILE_ID

(PosixPath('../../dist-s1-research/marshak/Zg_validation_variation/val_products_transformer_optimized-max10_processed_2026-02-05/treelosswet__20KNG'),
 '20KNG')

In [65]:
import rasterio
from rasterio.windows import Window
from pyproj import Transformer

def get_pixel_value(tif, lon, lat):
    with rasterio.open(tif) as src:
        transformer = Transformer.from_crs("EPSG:4326", src.crs, always_xy=True)
        
        x_utm, y_utm = transformer.transform(lon, lat)
        row, col = src.index(x_utm, y_utm)
        if row < 0 or row >= src.height or col < 0 or col >= src.width:
            raise ValueError("Point is outside the bounds of the raster")
        
        # Create window and read pixel value
        window = Window(col, row, 1, 1)
        val = src.read(1, window=window)[0, 0]
    
    return val

In [66]:
mgrs_ts_prods = sorted(list(TS_DIR.glob('OPERA*/')))
mgrs_ts_prods[:2]

[PosixPath('../../dist-s1-research/marshak/Zg_validation_variation/val_products_transformer_optimized-max10_processed_2026-02-05/treelosswet__20KNG/OPERA_L3_DIST-ALERT-S1_T20KNG_20240111T094330Z_20260205T195303Z_S1A_30_v0.1'),
 PosixPath('../../dist-s1-research/marshak/Zg_validation_variation/val_products_transformer_optimized-max10_processed_2026-02-05/treelosswet__20KNG/OPERA_L3_DIST-ALERT-S1_T20KNG_20240123T094330Z_20260205T193356Z_S1A_30_v0.1')]

In [67]:
mgrs_ts_status = [prod_dir / f'{prod_dir.name}_GEN-DIST-STATUS.tif' for prod_dir in mgrs_ts_prods]
mgrs_ts_status[:2]

[PosixPath('../../dist-s1-research/marshak/Zg_validation_variation/val_products_transformer_optimized-max10_processed_2026-02-05/treelosswet__20KNG/OPERA_L3_DIST-ALERT-S1_T20KNG_20240111T094330Z_20260205T195303Z_S1A_30_v0.1/OPERA_L3_DIST-ALERT-S1_T20KNG_20240111T094330Z_20260205T195303Z_S1A_30_v0.1_GEN-DIST-STATUS.tif'),
 PosixPath('../../dist-s1-research/marshak/Zg_validation_variation/val_products_transformer_optimized-max10_processed_2026-02-05/treelosswet__20KNG/OPERA_L3_DIST-ALERT-S1_T20KNG_20240123T094330Z_20260205T193356Z_S1A_30_v0.1/OPERA_L3_DIST-ALERT-S1_T20KNG_20240123T094330Z_20260205T193356Z_S1A_30_v0.1_GEN-DIST-STATUS.tif')]

In [68]:
mgrs_ts_dates = [pd.to_datetime(prod_dir.name.split('_')[4]).date() for prod_dir in mgrs_ts_prods]
mgrs_ts_dates[:2]

[datetime.date(2024, 1, 11), datetime.date(2024, 1, 23)]

# Dist Tables

In [69]:
df_val = pd.read_csv('../tables/reference_data/selectedpointsLL.csv')
df_val

,ID,Block,subID,blockStratum,substratum,zone,x,y,centx,centy,long,lat,MGRS
0,30961_1,30961,1,treelossTF,3,33,372932.570128,5.453950e+05,372945,545385,13.854048,4.933158,33NUF
1,30961_2,30961,2,treelossTF,2,33,372728.616472,5.425860e+05,372735,542595,13.852197,4.907920,33NUF
2,30961_3,30961,3,treelossTF,1,33,373846.916077,5.470932e+05,373845,547095,13.862138,4.948639,33NUF
3,30961_4,30961,4,treelossTF,4,33,371390.914129,5.460691e+05,371385,546075,13.839969,4.939375,33NUF
4,30961_5,30961,5,treelossTF,3,33,374504.487544,5.464576e+05,374505,546465,13.868099,4.942951,33NUF
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1828,1473302_16,1473302,16,oldcrop_short,2,21,375509.165457,-4.203209e+06,375495,-4203195,-58.417441,-37.967845,21HUU
1829,1473302_17,1473302,17,oldcrop_short,2,21,378407.482557,-4.204245e+06,378405,-4204245,-58.384499,-37.977701,21HUU
1830,1473302_18,1473302,18,oldcrop_short,1,21,374961.521864,-4.197591e+06,374955,-4197585,-58.422612,-37.917224,21HUU
1831,1473302_19,1473302,19,oldcrop_short,4,21,380894.210195,-4.196291e+06,380895,-4196295,-58.354839,-37.906398,21HUU
1832,1473302_20,1473302,20,oldcrop_short,1,21,380125.237247,-4.195666e+06,380115,-4195665,-58.363604,-37.900619,21HUU

In [70]:
df_val_mgrs = df_val[df_val['MGRS'] == MGRS_TILE_ID].reset_index(drop=True)
sites_in_mgrs_tile = df_val_mgrs.to_dict(orient='records')
sites_in_mgrs_tile[:2]

[{'ID': '1416380_1',
  'Block': 1416380,
  'subID': 1,
  'blockStratum': 'treelosswet',
  'substratum': 1,
  'zone': 20,
  'x': 510768.145166516,
  'y': -1807190.59948354,
  'centx': 510765,
  'centy': -1807185,
  'long': -62.8992094855683,
  'lat': -16.3457626876745,
  'MGRS': '20KNG'},
 {'ID': '1416380_2',
  'Block': 1416380,
  'subID': 2,
  'blockStratum': 'treelosswet',
  'substratum': 3,
  'zone': 20,
  'x': 514095.208554208,
  'y': -1803693.68695735,
  'centx': 514095,
  'centy': -1803705,
  'long': -62.8680525203614,
  'lat': -16.3142859020205,
  'MGRS': '20KNG'}]

In [71]:
tables = []
for site in tqdm(sites_in_mgrs_tile[:], desc='Processing sites'):
    site_id = site['ID']
    site_lon = site['long']
    site_lat = site['lat'] 

    labels = [get_pixel_value(tif, site_lon, site_lat) for tif in mgrs_ts_status]

    df_dist_s1_table_site = pd.DataFrame({
        'site_id': [site_id] * len(labels),
        'date': mgrs_ts_dates,
        # 'longitude': [site_lon] * len(labels),
        # 'latitude': [site_lat] * len(labels),
        'labels': labels,
    })
    tables.append(df_dist_s1_table_site)

tables[0].head()

Processing sites:   0%|          | 0/20 [00:00<?, ?it/s]

     site_id        date  labels
0  1416380_1  2024-01-11       0
1  1416380_1  2024-01-23       0
2  1416380_1  2024-02-04       0
3  1416380_1  2024-02-16       0
4  1416380_1  2024-02-28       0

In [72]:
tables[1].head(20)

      site_id        date  labels
0   1416380_2  2024-01-11       0
1   1416380_2  2024-01-23       0
2   1416380_2  2024-02-04       0
3   1416380_2  2024-02-16       0
4   1416380_2  2024-02-28       0
5   1416380_2  2024-03-11       0
6   1416380_2  2024-03-23       0
7   1416380_2  2024-04-04       0
8   1416380_2  2024-04-16       0
9   1416380_2  2024-04-28       0
10  1416380_2  2024-05-10       0
11  1416380_2  2024-06-03       0
12  1416380_2  2024-06-27       1
13  1416380_2  2024-07-09       2
14  1416380_2  2024-07-21       2
15  1416380_2  2024-08-02       2
16  1416380_2  2024-08-14       3
17  1416380_2  2024-08-26       3
18  1416380_2  2024-09-07       3
19  1416380_2  2024-09-19       3

In [73]:
for table in tables:
    site_id = table['site_id'].tolist()[0]
    block_id = site_id.split('_')[0]
    table_dir = Path(f'dist_s1_label_tables/{block_id}')
    table_dir.mkdir(exist_ok=True, parents=True)
    table_path = table_dir / f'{site_id}.csv'
    table.to_csv(table_path, index=False)

# Generate Site Vector Table

In [74]:
df_site_geo = gpd.GeoDataFrame(df_val_mgrs[['ID']],
                               geometry=gpd.points_from_xy(df_val_mgrs.long, 
                                                           df_val_mgrs.lat), 
                               crs=CRS.from_epsg(4326))
df_site_geo.head()

          ID                     geometry
0  1416380_1  POINT (-62.89921 -16.34576)
1  1416380_2  POINT (-62.86805 -16.31429)
2  1416380_3  POINT (-62.89414 -16.37261)
3  1416380_4  POINT (-62.86747 -16.35198)
4  1416380_5  POINT (-62.84757 -16.29502)

In [75]:
df_site_geo.to_file(table_dir / 'sites.geojson', driver='GeoJSON')